version: "3"

services:
  db:
    image: "mysql:latest"
    container_name: "car-spare-parts-mysql-db"
    ports:
      - "3307:3306"
    cap_add:
      - "SYS_NICE"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
